version: '3.7'

services:
  redis-token:
    image: redis:latest
    container_name: redis-token
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    networks:
      - tofu_net

  tofu-backend:
    image: phj0860/tofu-backend:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    restart: on-failure
    depends_on:
      - redis-token
    ports:
      - "9090:9090"
    networks:
      - tofu_net

  tofu-frontend:
    image: phj0860/tofu-frontend:latest
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - tofu_net

  tofu-mysql:
    image: mysql:8.0.25
    restart: on-failure
    container_name: tofu-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3410:3306"
    volumes:
      - type: volume
        source: tofu_mysql_data
        target: /var/lib/mysql
    networks:
      - tofu_net
    environment:
      MYSQL_DATABASE: tofu_db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/tofu_root_password    # secrets 파일 사용 시에는 prefix로 _FILE 필수
      MYSQL_USER_FILE: /run/secrets/tofu_user
      MYSQL_PASSWORD_FILE: /run/secrets/tofu_db_password
    secrets:
      - tofu_root_password
      - tofu_user
      - tofu_db_password


secrets:
  tofu_root_password:
    file: /run/secrets/tofu_root_password.txt
  tofu_user:
    file: /run/secrets/tofu_user.txt
  tofu_db_password:
    file: /run/secrets/tofu_db_password.txt

volumes:
  tofu_mysql_data:

networks:
  tofu_net:
    driver: bridge
    attachable: false
