name: tofu-hansol CD

on:
   pull_request:
     branches: [ master ]
     types: [ closed ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Application Run
        uses: appleboy/ssh-action@master
        env:
          PROJECT: tofu-hansol
          TOFU_BACKEND: tofu-backend
          TOFU_FRONTEND: tofu-frontend
        with:
          host: ${{ secrets.SERVER_SSH_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          envs: PROJECT, TOFU_BACKEND, TOFU_FRONTEND
          script: |
            echo $PROJECT
            echo $PROJECT > result.txt
            echo $TOFU_BACKEND
            echo $TOFU_FRONTEND >> result.txt
            cd ~/$PROJECT/$TOFU_BACKEND
            echo "1" >> result.txt
            git fetch -a
            echo "2" >> result.txt
            git checkout master
            echo "3" >> result.txt
            git pull
            echo "4" >> result.txt
            cd docker
            echo "5" >> result.txt
            echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
            echo "6" >> result.txt
            sudo docker rm -f $(docker ps -q -a)
            docker-compose pull
            docker-compose up -d
            docker image prune -f
            

